# Generated by Django 5.2.6 on 2025-12-03 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="FontAwesome class e.g. 'fas fa-leaf'", max_length=50)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10)),
                ('condition_key', models.CharField(help_text="Code reference, e.g., 'log_7_days_streak'", max_length=100, unique=True)),
                ('xp_reward', models.IntegerField(default=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avg_daily_emission_kg',
            field=models.FloatField(default=0.0, help_text='Used for Heatmap coloring'),
        ),
        migrations.AddField(
            model_name='profile',
            name='carbon_budget_kg',
            field=models.FloatField(default=500.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='eco_coins',
            field=models.IntegerField(default=0, help_text='Currency earned via sustainable actions. Can be spent on rewards.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_iot_connected',
            field=models.BooleanField(default=False, help_text='True if the user has linked a hardware energy meter.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sustainability_score',
            field=models.IntegerField(default=0, help_text='A normalized score (0-100) indicating user eco-performance.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_emission_kg',
            field=models.FloatField(default=0.0, help_text='Lifetime emission'),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transportation'), ('energy', 'Home Energy'), ('food', 'Food'), ('consumption', 'Purchases'), ('waste', 'Waste')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('carbon_footprint_kg', models.FloatField(help_text='Calculated result')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('iot', 'IoT Device')], default='manual', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('University', 'University'), ('Corporate', 'Corporate'), ('Neighborhood', 'Neighborhood')], max_length=50)),
                ('total_community_emission', models.FloatField(default=0.0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communities', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='joined_communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_metric', models.CharField(choices=[('emission_reduction', 'Emission Reduction'), ('activity_count', 'Log Count')], max_length=50)),
                ('target_value', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reward_xp', models.IntegerField(default=100)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
