# Generated by Django 5.2.6 on 2026-01-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_organization_profile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_pin',
            field=models.CharField(default='202510', help_text='6-digit PIN for Org Login', max_length=6),
        ),
    ]
