# Generated by Django 5.2.6 on 2026-02-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_organization_email_organization_org_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('HR', 'Human Resources'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Operations', 'Operations'), ('Finance', 'Finance'), ('Engineering', 'Engineering'), ('Legal', 'Legal'), ('Other', 'Other')], default=None, max_length=50, null=True),
        ),
    ]
